### ISSUE TITLE
Link for sharing CF Template

### ISSUE THREAD

**Issue by rfitzhugh** [rubrikinc/use-case-aws-cloudformation-template-cloudcluster#4]
The template needs to be uploaded and shared out via an AWS link like the rest of the CF templates. 

For example: https://s3-us-west-1.amazonaws.com/cloudformation-templates-rubrik-prod/rubrik_cloudon.template

**Comment by drew-russell** [comment]
https://s3-us-west-1.amazonaws.com/cloudformation-templates-rubrik-prod/rubrik_cloudcluster.template
